// export const closeButton = "Закрыть";
// export const downloadButton = "Скачать";
// export const nextImageButton = "Следующая картинка";
// export const prevImageButton = "Предыдущая картинка";
export const closeButton = "Close";
export const downloadButton = "Download";
export const nextImageButton = "Next";
export const prevImageButton = "Previous";
export const infoButton = "More information";